unbind r
bind r source-file ~/.tmux.conf

# QoL
set -g prefix C-s
set -g mouse on

# vim keybindings (im a nerd)
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -g @plugin 'tmux-plugins/tpm'
set -g default-terminal "tmux-256color"


# lol ricers do allat, I just make it transparent

# america time
set-window-option -g clock-mode-style 12

# status left and right
set -g status-right "hello, #h "
# set -g status-right "#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}\"#{=21:pane_title}\" %a %b %e,%l:%M %p" 
set -g status-left " #{session_name}, btw"

# simple transparency
set -g status-bg default
set -g status-style bg=default

# catppuccin mocha colors
set -ag pane-active-border fg="#cba6f7"
# center
set -g status-justify absolute-centre
set -g status-position top
# yazi
set -g allow-passthrough on
set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM
# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
# I dont have any plugins rn so I dont run it
#run '~/.tmux/plugins/tpm/tpm'
